# Generated by Django 4.1.1 on 2022-09-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reportajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(max_length=50)),
                ('reportero', models.CharField(max_length=100)),
                ('camarografo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('clip', models.CharField(max_length=10)),
                ('clipdiferetes', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('tema', models.CharField(max_length=500)),
            ],
        ),
    ]
