# Generated by Django 4.1.1 on 2022-09-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0002_remove_reportajes_id_alter_reportajes_disco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reportajes',
            new_name='reportaje',
        ),
    ]
