# Generated by Django 4.1.1 on 2022-09-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0003_rename_reportajes_reportaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaje',
            name='estatus',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportaje',
            name='realizo',
            field=models.CharField(default=str, max_length=150),
            preserve_default=False,
        ),
    ]
