# Generated by Django 4.1.1 on 2022-09-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0004_reportaje_estatus_reportaje_realizo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportaje',
            name='fecha',
            field=models.DateField(),
        ),
    ]
