# Generated by Django 4.1.1 on 2022-09-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0005_alter_reportaje_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportaje',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
