# Generated by Django 4.1.1 on 2022-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0006_alter_reportaje_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='camarografo',
            fields=[
                ('id_camarografo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reporteros',
            fields=[
                ('id_reportero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
