# Generated by Django 4.1.1 on 2022-10-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0007_camarografo_reporteros_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reporteros',
            new_name='reporteross',
        ),
    ]
