# Generated by Django 4.1.1 on 2022-10-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0008_rename_reporteros_reporteross'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camarografo',
            old_name='correo',
            new_name='coreo',
        ),
    ]
