# Generated by Django 4.1.1 on 2022-10-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0009_rename_correo_camarografo_coreo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camarografo',
            old_name='coreo',
            new_name='correo',
        ),
    ]
