# Generated by Django 4.1.1 on 2022-10-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0010_rename_coreo_camarografo_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
    ]
