# Generated by Django 4.1.1 on 2022-10-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0012_camarografo_contrasena_reporteross_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camarografo',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='reporteross',
            name='contrasena',
        ),
    ]
