# Generated by Django 4.1.1 on 2022-10-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportajes', '0013_remove_camarografo_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camarografo',
            name='contrasena',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteross',
            name='contrasena',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
    ]
